const types = {

    CHECK_USER_BEGIN: 'CHECK_USER_BEGIN',
    CHECK_USER_SUCCESS: 'CHECK_USER_SUCCESS',
    CHECK_USER_FAILURE: 'CHECK_USER_FAILURE',
    FETCH_REPO_BEGIN:'FETCH_REPO_BEGIN',
    FETCH_REPO_SUCCESS: 'FETCH_REPO_SUCCESS',
    FETCH_REPO_FAILURE: 'FETCH_REPO_FAILURE',
    FETCH_ORG_BEGIN: 'FETCH_ORG_BEGIN',
    FETCH_ORG_SUCCESS: 'FETCH_ORG_SUCCESS',
    FETCH_ORG_FAILURE: 'FETCH_ORG_FAILURE',
    TO_SEARCH: 'TO_SEARCH',
};

export default types;